apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
    visualize: "true"
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
        visualize: "true"
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017