apiVersion: v1
kind: Service
metadata:
  labels:
    name: read-verticle
    visualize: "true"
    vertx-cluster: "true"
  name: read-verticle
spec:
  ports:
    - port: 5701
      name: hazelcast
  selector:
    app: vertx-cluster-01
