apiVersion: v1
kind: Service
metadata:
  labels:
    name: read-verticle
    visualize: "true"
    vertx-cluster: "true"
  name: read-verticle
spec:
  ports:
    - port: 8282
      targetPort: 8282
  selector:
    app: vertx-cluster-01
