apiVersion: v1
kind: Service
metadata:
  labels:
    name: write-verticle
    visualize: "true"
    vertx-cluster: "true"
  name: write-verticle
spec:
  ports:
    - port: 8383
      targetPort: 8383
  selector:
    app: vertx-cluster-02
