apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway-vxms
    visualize: "true"
    vertx-cluster: "true"
  name: gateway-vxms
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8181
      name: gateway-vxms
  selector:
      app:  vxms-cluster
