apiVersion: v1
kind: Service
metadata:
  labels:
    name: write-vxms
    visualize: "true"
    vertx-cluster: "true"
  name: write-vxms
spec:
  ports:
    - port: 5701
      name: hazelcast
  selector:
    app: vxms-cluster-02
