apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: write-vxms
    visualize: "true"
  name: write-vxms-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: write-vxms
        env: prod
        app: vxms-cluster-02
        visualize: "true"
    spec:
      containers:
      - image: gcr.io/kubernetestests-147607/write-verticle:vxms-demo
        name: write-vxms
        ports:
        - name: hazelcast
          containerPort: 5701
